// <auto-generated />
using System;
using ManutencaoAtivos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManutencaoAtivos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108170932_InitialCreate_IntId")]
    partial class InitialCreate_IntId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("ManutencaoAtivos.Models.Caminhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataUltimaRevisao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Km")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximaRevisao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Caminhao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2014,
                            DataUltimaRevisao = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 120000,
                            Modelo = "Scania",
                            Placa = "PUU8869",
                            ProximaRevisao = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2016,
                            DataUltimaRevisao = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 95000,
                            Modelo = "Volvo",
                            Placa = "AAA1234",
                            ProximaRevisao = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2018,
                            DataUltimaRevisao = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 87000,
                            Modelo = "Mercedes-Benz",
                            Placa = "BBB5678",
                            ProximaRevisao = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2020,
                            DataUltimaRevisao = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 64000,
                            Modelo = "Iveco",
                            Placa = "CCC9012",
                            ProximaRevisao = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2017,
                            DataUltimaRevisao = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 110000,
                            Modelo = "DAF",
                            Placa = "DDD3456",
                            ProximaRevisao = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 78000,
                            Modelo = "Scania",
                            Placa = "EEE7890",
                            ProximaRevisao = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 2013,
                            DataUltimaRevisao = new DateTime(2023, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 210000,
                            Modelo = "Volvo",
                            Placa = "FFF2345",
                            ProximaRevisao = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 2015,
                            DataUltimaRevisao = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 156000,
                            Modelo = "MAN",
                            Placa = "GGG6789",
                            ProximaRevisao = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 2021,
                            DataUltimaRevisao = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 52000,
                            Modelo = "Mercedes-Benz",
                            Placa = "HHH0123",
                            ProximaRevisao = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2012,
                            DataUltimaRevisao = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 280000,
                            Modelo = "Iveco",
                            Placa = "III4567",
                            ProximaRevisao = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 11,
                            Ano = 2016,
                            DataUltimaRevisao = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 143000,
                            Modelo = "Scania",
                            Placa = "JJJ8901",
                            ProximaRevisao = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 12,
                            Ano = 2018,
                            DataUltimaRevisao = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 89000,
                            Modelo = "DAF",
                            Placa = "KKK1357",
                            ProximaRevisao = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 13,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 70000,
                            Modelo = "Volvo",
                            Placa = "LLL2468",
                            ProximaRevisao = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 14,
                            Ano = 2014,
                            DataUltimaRevisao = new DateTime(2023, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 198000,
                            Modelo = "MAN",
                            Placa = "MMM3691",
                            ProximaRevisao = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 15,
                            Ano = 2017,
                            DataUltimaRevisao = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 124000,
                            Modelo = "Mercedes-Benz",
                            Placa = "NNN4826",
                            ProximaRevisao = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2013,
                            DataUltimaRevisao = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 210000,
                            Modelo = "Scania",
                            Placa = "OOO5937",
                            ProximaRevisao = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 17,
                            Ano = 2020,
                            DataUltimaRevisao = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 62000,
                            Modelo = "Iveco",
                            Placa = "PPP6048",
                            ProximaRevisao = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 18,
                            Ano = 2015,
                            DataUltimaRevisao = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 154000,
                            Modelo = "DAF",
                            Placa = "QQQ7159",
                            ProximaRevisao = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 19,
                            Ano = 2018,
                            DataUltimaRevisao = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 94000,
                            Modelo = "Volvo",
                            Placa = "RRR8260",
                            ProximaRevisao = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 20,
                            Ano = 2016,
                            DataUltimaRevisao = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 132000,
                            Modelo = "Scania",
                            Placa = "SSS9371",
                            ProximaRevisao = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 21,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 81000,
                            Modelo = "Mercedes-Benz",
                            Placa = "TTT0482",
                            ProximaRevisao = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 22,
                            Ano = 2015,
                            DataUltimaRevisao = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 177000,
                            Modelo = "MAN",
                            Placa = "UUU1593",
                            ProximaRevisao = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 23,
                            Ano = 2017,
                            DataUltimaRevisao = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 120000,
                            Modelo = "Volvo",
                            Placa = "VVV2604",
                            ProximaRevisao = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 24,
                            Ano = 2020,
                            DataUltimaRevisao = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 67000,
                            Modelo = "Scania",
                            Placa = "WWW3715",
                            ProximaRevisao = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 25,
                            Ano = 2021,
                            DataUltimaRevisao = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 54000,
                            Modelo = "Iveco",
                            Placa = "XXX4826",
                            ProximaRevisao = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 26,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 90000,
                            Modelo = "DAF",
                            Placa = "YYY5937",
                            ProximaRevisao = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 27,
                            Ano = 2016,
                            DataUltimaRevisao = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 130000,
                            Modelo = "Volvo",
                            Placa = "ZZZ6048",
                            ProximaRevisao = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 28,
                            Ano = 2018,
                            DataUltimaRevisao = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 95000,
                            Modelo = "Scania",
                            Placa = "ABC7159",
                            ProximaRevisao = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 29,
                            Ano = 2014,
                            DataUltimaRevisao = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 205000,
                            Modelo = "MAN",
                            Placa = "DEF8260",
                            ProximaRevisao = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 30,
                            Ano = 2021,
                            DataUltimaRevisao = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 48000,
                            Modelo = "Mercedes-Benz",
                            Placa = "GHI9371",
                            ProximaRevisao = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 31,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 82000,
                            Modelo = "Volvo",
                            Placa = "JKL0482",
                            ProximaRevisao = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 32,
                            Ano = 2020,
                            DataUltimaRevisao = new DateTime(2024, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 61000,
                            Modelo = "Scania",
                            Placa = "MNO1593",
                            ProximaRevisao = new DateTime(2025, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 33,
                            Ano = 2017,
                            DataUltimaRevisao = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 125000,
                            Modelo = "Iveco",
                            Placa = "PQR2604",
                            ProximaRevisao = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 34,
                            Ano = 2013,
                            DataUltimaRevisao = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 230000,
                            Modelo = "DAF",
                            Placa = "STU3715",
                            ProximaRevisao = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 35,
                            Ano = 2015,
                            DataUltimaRevisao = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 175000,
                            Modelo = "Volvo",
                            Placa = "VWX4826",
                            ProximaRevisao = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 36,
                            Ano = 2018,
                            DataUltimaRevisao = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 93000,
                            Modelo = "Mercedes-Benz",
                            Placa = "YZA5937",
                            ProximaRevisao = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 37,
                            Ano = 2016,
                            DataUltimaRevisao = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 150000,
                            Modelo = "MAN",
                            Placa = "BCD6048",
                            ProximaRevisao = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 38,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 78000,
                            Modelo = "Scania",
                            Placa = "EFG7159",
                            ProximaRevisao = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 39,
                            Ano = 2021,
                            DataUltimaRevisao = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 40000,
                            Modelo = "Volvo",
                            Placa = "HIJ8260",
                            ProximaRevisao = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 40,
                            Ano = 2017,
                            DataUltimaRevisao = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 122000,
                            Modelo = "DAF",
                            Placa = "KLM9371",
                            ProximaRevisao = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 41,
                            Ano = 2020,
                            DataUltimaRevisao = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 65000,
                            Modelo = "Scania",
                            Placa = "NOP0482",
                            ProximaRevisao = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 42,
                            Ano = 2018,
                            DataUltimaRevisao = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 98000,
                            Modelo = "Volvo",
                            Placa = "QRS1593",
                            ProximaRevisao = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 43,
                            Ano = 2015,
                            DataUltimaRevisao = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 162000,
                            Modelo = "Mercedes-Benz",
                            Placa = "TUV2604",
                            ProximaRevisao = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 44,
                            Ano = 2014,
                            DataUltimaRevisao = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 208000,
                            Modelo = "MAN",
                            Placa = "WXY3715",
                            ProximaRevisao = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 45,
                            Ano = 2022,
                            DataUltimaRevisao = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 30000,
                            Modelo = "DAF",
                            Placa = "ZAB4826",
                            ProximaRevisao = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 46,
                            Ano = 2023,
                            DataUltimaRevisao = new DateTime(2024, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 18000,
                            Modelo = "Scania",
                            Placa = "CDE5937",
                            ProximaRevisao = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 47,
                            Ano = 2019,
                            DataUltimaRevisao = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 85000,
                            Modelo = "Volvo",
                            Placa = "FGH6048",
                            ProximaRevisao = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 48,
                            Ano = 2017,
                            DataUltimaRevisao = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 118000,
                            Modelo = "Mercedes-Benz",
                            Placa = "IJK7159",
                            ProximaRevisao = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 49,
                            Ano = 2020,
                            DataUltimaRevisao = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 60000,
                            Modelo = "MAN",
                            Placa = "LMN8260",
                            ProximaRevisao = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 50,
                            Ano = 2016,
                            DataUltimaRevisao = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Km = 134000,
                            Modelo = "Volvo",
                            Placa = "OPQ9371",
                            ProximaRevisao = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ativo"
                        });
                });

            modelBuilder.Entity("ManutencaoAtivos.Models.HistoricoManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoServico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoricoManutencao");
                });

            modelBuilder.Entity("ManutencaoAtivos.Models.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhaoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Custo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoManutencao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrdemServico");
                });
#pragma warning restore 612, 618
        }
    }
}
